### ISSUE TITLE
As a student, I can edit tags

### ISSUE THREAD

**Issue by ChongCheeKaiClarence** [AY2223S1-CS2103T-W15-1/tp#9]
... so that I can provide better naming.

For example:
`tag edit t/friend t/bestFriend` changes the friend tag to a bestFriend tag.

**Comment by florentianayuwono** [comment]
Hi, I have just tested and played around, but not sure whether these bugs are intentional or not.

- When we edit a tag, can we also edit a tag that is created via adding contact? For example, I found out that I can edit a tag only if I type like this:
1. `tag create t/family`.
2. `tag edit t/family t/notfamily`, it then shows confirmation message that I have changed the tag.
But when I do like this:
1. `add n/John t/friend`.
2. `tag edit t/friend t/bestfriend`, it then shows that the tag doesn't exist.

- Also, inconsistencies are found in the User Guide:
1. `Format: tag edit t/TAG1 t/ TAG2` should have been `Format: tag edit t/TAG1 t/TAG2`.
2. For adding tag to a contact, user guide says: `Format: tag add n/NAME t/TAG`, but in practice it throws an error and specify that the format should be `tag add INDEX t/TAG`.

- Confirmation message when editing tag only shows `Tag has changed from `, I think it meant to show `Tag has changed from OLDTAG to NEWTAG`.

- When I edit a tag, the old tag stays in the contact, it is not dynamically changed. For example, let's say I have associated `John` with `friend`. When I change tag `friend` to `bestfriend`, the list still displays `John` as `friend`.

**Comment by Eugene-Ong-W-X** [comment]
@florentianayuwono Since the documentation will be done later, we can ignore the inconsistencies with the user guide, at least until we start doing the documentation

**Comment by Eugene-Ong-W-X** [comment]
Apparently, the tags added to a contact via the `add` command do not respond to the new `tag edit` command. 
So I can think of 2 paths to fix this
1. disable adding of tags when adding new contacts via the `add command
2. incorporate `tag create` and/or `tag add` command to the `add` command for when the user adds a new/existing tag when adding a new contact

What do you all think?

**Comment by ChongCheeKaiClarence** [comment]
Yes, Florentiana. I apologize for not communicating about the problems I faced with my features.

The `AddCommand` and `EditCommand` have their own implementation of adding and editing tags.
I am unsure whether we want to allow `AddCommand` and `EditCommand` to create tags on their own, only use tags from the tagList, or disable them from adding or editing tags.

Due to the statement above, I chose not to change `AddCommand` and `EditCommand` implementation before deciding on what to do with their `t/` command.

I also chose to have `tag edit` to not directly affect the tags in the contacts yet due to the same reasoning stated above.

I thought maybe I could clarify these issues in the next meeting.

Once again, I am sorry for the confusion.

Currently, I am in agreement with Eugene's 1st solution to the issue. If everyone agrees, I will make changes accordingly.

**Comment by Eugene-Ong-W-X** [comment]
@ChongCheeKaiClarence Which path would be easier for you to implement for v1.2? Path 1 or Path 2?

**Comment by PangKuangWei** [comment]
Path 1 seems to be the safer option.

**Comment by florentianayuwono** [comment]
For @ChongCheeKaiClarence no need to apologize haha, I was just playing around. Also, I agree that path 1 is safer and might be easier too👍
